// AUTO-GENERATED by scripts/generate-news.mjs — do not edit by hand.
// Regenerate with: node scripts/generate-news.mjs

export const newsData = [
  {
    "slug": "messi-brace-argentina-pimpin-grup-c",
    "title": "Messi Cetak Brace, Argentina Pimpin Grup C di Laga Panas Lawan Brasil",
    "excerpt": "Lionel Messi kembali jadi penentu saat Argentina mengalahkan Brasil 2-1 dalam laga klasik Amerika Selatan yang berlangsung sengit hingga menit akhir.",
    "category": "Piala Dunia",
    "author": "Rangga Aditya",
    "time": "12 menit lalu",
    "order": 1,
    "featured": true,
    "html": "<p>Estadio Azteca menjadi saksi laga klasik Amerika Selatan yang berlangsung penuh tensi. <strong>Argentina</strong> memastikan tiga poin penting usai mengalahkan <strong>Brasil</strong> dengan skor <strong>2-1</strong> dan kini memimpin klasemen Grup C.</p>\n<h2>Messi tampil menentukan</h2>\n<p>Lionel Messi membuka keunggulan pada menit ke-31 lewat tendangan bebas spektakuler yang gagal dijangkau kiper Brasil. Sang kapten kembali mencatatkan namanya di papan skor pada babak kedua, menggenapkan brace-nya sekaligus memecah kebuntuan setelah Brasil sempat menyamakan kedudukan.</p>\n<blockquote>\n<p>&quot;Kami tahu laga ini akan sulit. Brasil tim hebat, tapi malam ini milik kami,&quot; ujar Messi seusai pertandingan.</p>\n</blockquote>\n<h2>Jalannya pertandingan</h2>\n<ul>\n<li><strong>31&#39;</strong> — Messi membuka skor lewat tendangan bebas</li>\n<li><strong>58&#39;</strong> — Brasil menyamakan kedudukan melalui serangan balik cepat</li>\n<li><strong>74&#39;</strong> — Messi mencetak gol kemenangan dari titik penalti</li>\n</ul>\n<p>Pelatih Argentina memuji mental para pemainnya yang tetap tenang meski mendapat tekanan bertubi-tubi di babak kedua.</p>\n<h2>Apa selanjutnya?</h2>\n<p>Dengan kemenangan ini, Argentina kokoh di puncak Grup C dengan poin sempurna. Brasil masih punya peluang lolos, namun wajib menang pada laga pamungkas melawan Meksiko.</p>\n"
  },
  {
    "slug": "timnas-indonesia-lolos-16-besar",
    "title": "Resmi: Timnas Indonesia Lolos ke Babak 16 Besar untuk Pertama Kali",
    "excerpt": "Sejarah baru tercipta. Garuda memastikan satu tempat di fase gugur setelah hasil imbang yang dramatis.",
    "category": "Timnas",
    "author": "Dewi Lestari",
    "time": "45 menit lalu",
    "order": 2,
    "featured": false,
    "html": "<p>Sejarah baru akhirnya tercipta. <strong>Timnas Indonesia</strong> memastikan diri lolos ke babak 16 besar Piala Dunia untuk pertama kalinya sepanjang sejarah, setelah bermain imbang dramatis di laga pamungkas fase grup.</p>\n<h2>Drama hingga menit akhir</h2>\n<p>Garuda hanya membutuhkan hasil seri untuk lolos, namun harus melewati momen-momen menegangkan. Gol penyeimbang di masa injury time memastikan tiket ke fase gugur tetap berada di tangan skuad Merah Putih.</p>\n<p>Stadion dipenuhi suporter Indonesia yang langsung larut dalam euforia begitu wasit meniup peluit panjang.</p>\n<h2>Reaksi pelatih</h2>\n<blockquote>\n<p>&quot;Para pemain ini menulis sejarah. Mereka pantas mendapatkannya,&quot; kata pelatih kepala dengan mata berkaca-kaca.</p>\n</blockquote>\n<h2>Lawan di 16 besar</h2>\n<p>Indonesia akan menghadapi salah satu tim unggulan pada babak gugur. Meski berstatus underdog, semangat dan kekompakan skuad menjadi modal utama untuk membuat kejutan lebih jauh.</p>\n"
  },
  {
    "slug": "prediksi-spanyol-vs-jerman",
    "title": "Prediksi Spanyol vs Jerman: Duel Tiki-Taka Melawan Efisiensi",
    "excerpt": "Dua raksasa Eropa bertemu malam ini. Siapa yang akan menguasai lini tengah?",
    "category": "Preview",
    "author": "Bayu Saputra",
    "time": "1 jam lalu",
    "order": 3,
    "featured": false,
    "html": "<p>Laga besar tersaji malam ini di SoFi Stadium. <strong>Spanyol</strong> dan <strong>Jerman</strong>, dua raksasa sepak bola Eropa, akan saling berhadapan dalam duel yang menentukan puncak klasemen Grup B.</p>\n<h2>Filosofi yang berbeda</h2>\n<p>Spanyol datang dengan gaya penguasaan bola khasnya, mengandalkan umpan-umpan pendek dan pergerakan tanpa bola. Di sisi lain, Jerman tampil lebih pragmatis dengan transisi cepat dan efisiensi tinggi di depan gawang.</p>\n<h2>Pemain kunci</h2>\n<ul>\n<li><strong>Spanyol:</strong> kreativitas lini tengah jadi nyawa serangan</li>\n<li><strong>Jerman:</strong> ketajaman penyerang di kotak penalti</li>\n</ul>\n<h2>Prediksi skor</h2>\n<p>Pertandingan diprediksi berlangsung ketat. Penguasaan bola kemungkinan didominasi Spanyol, namun Jerman berbahaya lewat serangan balik. Prediksi kami: <strong>2-2</strong>, sebuah laga terbuka yang sayang untuk dilewatkan.</p>\n"
  },
  {
    "slug": "top-skor-mbappe-5-gol",
    "title": "Top Skor Sementara: Mbappé Memimpin dengan 5 Gol",
    "excerpt": "Persaingan sepatu emas memanas memasuki pekan kedua turnamen.",
    "category": "Statistik",
    "author": "Tim Bolakami",
    "time": "2 jam lalu",
    "order": 4,
    "featured": false,
    "html": "<p>Persaingan perebutan <strong>sepatu emas</strong> semakin memanas memasuki pekan kedua turnamen. <strong>Kylian Mbappé</strong> memimpin daftar pencetak gol sementara dengan koleksi <strong>5 gol</strong>.</p>\n<h2>Daftar top skor sementara</h2>\n<ol>\n<li><strong>Kylian Mbappé</strong> (Prancis) — 5 gol</li>\n<li><strong>Lionel Messi</strong> (Argentina) — 4 gol</li>\n<li><strong>Harry Kane</strong> (Inggris) — 4 gol</li>\n<li><strong>Vinícius Jr</strong> (Brasil) — 3 gol</li>\n</ol>\n<h2>Persaingan ketat</h2>\n<p>Selisih gol antar pemain papan atas masih sangat tipis. Dengan beberapa laga fase grup yang tersisa serta babak gugur yang menanti, perebutan gelar pencetak gol terbanyak diprediksi berlangsung hingga laga final.</p>\n<p>Konsistensi dan ketajaman akan menjadi penentu siapa yang berhak membawa pulang penghargaan individu paling bergengsi di turnamen ini.</p>\n"
  },
  {
    "slug": "var-penalti-kontroversial-portugal",
    "title": "VAR Jadi Sorotan Usai Penalti Kontroversial di Laga Portugal",
    "excerpt": "Keputusan wasit menuai protes keras dari kubu lawan dan jadi perbincangan netizen.",
    "category": "Kontroversi",
    "author": "Indra Wijaya",
    "time": "3 jam lalu",
    "order": 5,
    "featured": false,
    "html": "<p>Teknologi <strong>VAR</strong> kembali menjadi pusat perhatian setelah keputusan penalti kontroversial mewarnai laga yang melibatkan <strong>Portugal</strong>. Keputusan wasit memicu protes keras dan langsung menjadi perbincangan hangat di media sosial.</p>\n<h2>Momen kontroversial</h2>\n<p>Insiden terjadi pada babak kedua ketika wasit menunjuk titik putih setelah meninjau ulang tayangan VAR. Kubu lawan menilai kontak yang terjadi tidak cukup untuk dihadiahi penalti.</p>\n<h2>Pro dan kontra</h2>\n<blockquote>\n<p>&quot;Keputusan seperti ini bisa mengubah jalannya turnamen. Kami butuh konsistensi,&quot; keluh salah satu pemain.</p>\n</blockquote>\n<p>Para pengamat terbelah. Sebagian menilai keputusan sudah tepat sesuai aturan, sementara yang lain menganggap intervensi VAR terlalu jauh dan mengganggu ritme permainan.</p>\n<h2>Perlunya evaluasi</h2>\n<p>Insiden ini kembali membuka diskusi soal standardisasi penggunaan VAR. Federasi diharapkan memberikan penjelasan terbuka agar polemik serupa tidak terus berulang di laga-laga berikutnya.</p>\n"
  },
  {
    "slug": "format-baru-48-tim-piala-dunia-2026",
    "title": "Format Baru 48 Tim: Begini Cara Kerja Fase Grup Piala Dunia 2026",
    "excerpt": "Untuk pertama kalinya Piala Dunia diikuti 48 negara. Simak format 12 grup dan jalur menuju babak gugur.",
    "category": "Piala Dunia",
    "author": "Rangga Aditya",
    "time": "4 jam lalu",
    "order": 6,
    "featured": false,
    "html": "<p>Piala Dunia 2026 menjadi tonggak sejarah baru: untuk pertama kalinya turnamen akbar ini diikuti oleh <strong>48 tim</strong>, naik dari 32 tim pada edisi sebelumnya.</p>\n<h2>12 grup berisi empat tim</h2>\n<p>Seluruh peserta dibagi ke dalam <strong>12 grup</strong> yang masing-masing berisi empat tim. Dua tim teratas dari setiap grup otomatis lolos ke babak gugur.</p>\n<h2>Jalur peringkat tiga terbaik</h2>\n<p>Selain juara dan runner-up grup, <strong>delapan tim peringkat ketiga terbaik</strong> juga berhak melaju. Total 32 tim akan mengisi babak 32 besar sebelum berlanjut ke 16 besar, perempat final, semifinal, dan final.</p>\n<h2>Lebih banyak laga</h2>\n<p>Format baru ini membuat jumlah pertandingan melonjak menjadi 104 laga. Konsekuensinya, turnamen berlangsung lebih panjang dan menuntut kedalaman skuad yang lebih besar dari setiap tim peserta.</p>\n"
  },
  {
    "slug": "tiga-tuan-rumah-piala-dunia-2026",
    "title": "Tiga Tuan Rumah: Piala Dunia 2026 Digelar di AS, Kanada, dan Meksiko",
    "excerpt": "Untuk pertama kalinya tiga negara menjadi tuan rumah bersama. Berikut sebaran kota dan stadion penyelenggara.",
    "category": "Piala Dunia",
    "author": "Dewi Lestari",
    "time": "5 jam lalu",
    "order": 7,
    "featured": false,
    "html": "<p>Piala Dunia 2026 menorehkan sejarah dengan menjadi edisi pertama yang digelar oleh <strong>tiga negara tuan rumah</strong> sekaligus: Amerika Serikat, Kanada, dan Meksiko.</p>\n<h2>Sebaran kota penyelenggara</h2>\n<p>Sebanyak 16 kota terpilih menjadi lokasi pertandingan, membentang dari pesisir barat hingga timur Amerika Utara. Amerika Serikat menjadi tuan rumah mayoritas laga, termasuk babak final.</p>\n<h2>Stadion ikonik</h2>\n<ul>\n<li><strong>Estadio Azteca</strong>, Mexico City — stadion bersejarah pembuka turnamen</li>\n<li><strong>MetLife Stadium</strong>, New Jersey — calon tempat laga final</li>\n<li><strong>SoFi Stadium</strong>, Los Angeles — arena berteknologi modern</li>\n</ul>\n<h2>Tantangan logistik</h2>\n<p>Jarak antarkota yang jauh dan perbedaan zona waktu menjadi tantangan tersendiri, baik bagi tim peserta maupun suporter yang ingin mengikuti perjalanan tim kesayangannya.</p>\n"
  },
  {
    "slug": "jadwal-babak-16-besar-piala-dunia-2026",
    "title": "Jadwal Lengkap Babak 16 Besar Piala Dunia 2026 dan Jalur ke Final",
    "excerpt": "Fase grup tuntas, 16 tim terbaik siap berlaga. Berikut bagan dan jadwal menuju partai puncak.",
    "category": "Piala Dunia",
    "author": "Bayu Saputra",
    "time": "6 jam lalu",
    "order": 8,
    "featured": false,
    "html": "<p>Fase grup telah usai dan menyisakan tim-tim terbaik yang siap bertarung di babak gugur. Berikut gambaran perjalanan menuju partai puncak.</p>\n<h2>Bagan babak 16 besar</h2>\n<p>Pemenang grup akan bertemu salah satu tim peringkat ketiga atau runner-up dari grup lain. Sistem ini dirancang agar tim-tim unggulan tidak saling bertemu terlalu dini.</p>\n<h2>Jadwal padat</h2>\n<p>Laga babak gugur digelar setiap hari dengan dua hingga tiga pertandingan. Tidak ada lagi ruang untuk kesalahan: kalah berarti tersingkir.</p>\n<h2>Menuju final</h2>\n<p>Pemenang 16 besar melaju ke perempat final, dilanjutkan semifinal, dan akhirnya partai final yang akan menentukan juara dunia baru. Persaingan diprediksi berlangsung sangat ketat di antara tim-tim favorit.</p>\n"
  },
  {
    "slug": "timnas-indonesia-hadapi-tim-unggulan-16-besar",
    "title": "Timnas Indonesia Hadapi Tim Unggulan di 16 Besar, Ini Persiapannya",
    "excerpt": "Setelah lolos bersejarah, Garuda bersiap menghadapi raksasa di fase gugur. Pelatih siapkan strategi khusus.",
    "category": "Timnas",
    "author": "Dewi Lestari",
    "time": "7 jam lalu",
    "order": 9,
    "featured": false,
    "html": "<p>Euforia lolosnya <strong>Timnas Indonesia</strong> ke babak 16 besar belum reda, namun fokus kini beralih ke laga berikutnya menghadapi salah satu tim unggulan turnamen.</p>\n<h2>Strategi bertahan disiplin</h2>\n<p>Pelatih kepala menegaskan timnya akan mengandalkan organisasi pertahanan yang rapi dan serangan balik cepat. Pendekatan realistis dinilai paling masuk akal menghadapi lawan yang secara materi lebih kuat.</p>\n<h2>Kondisi pemain</h2>\n<p>Kabar baik datang dari ruang ganti: seluruh pemain inti dalam kondisi bugar. Beberapa pemain yang sempat mengalami kelelahan telah pulih dan siap tampil maksimal.</p>\n<h2>Dukungan suporter</h2>\n<p>Ribuan suporter Indonesia diperkirakan memadati stadion. Dukungan ini diharapkan menjadi pemain kedua belas yang mengangkat semangat skuad Merah Putih untuk kembali membuat kejutan.</p>\n"
  },
  {
    "slug": "persaingan-sepatu-emas-piala-dunia-2026",
    "title": "Persaingan Sepatu Emas Memanas: Mbappé, Messi, dan Kane Bersaing Ketat",
    "excerpt": "Perebutan gelar pencetak gol terbanyak Piala Dunia 2026 berlangsung sengit memasuki babak gugur.",
    "category": "Statistik",
    "author": "Tim Bolakami",
    "time": "8 jam lalu",
    "order": 10,
    "featured": false,
    "html": "<p>Perebutan <strong>Sepatu Emas</strong> Piala Dunia 2026 menjadi salah satu sub-cerita paling menarik di tengah ketatnya persaingan antartim.</p>\n<h2>Papan atas yang rapat</h2>\n<p>Kylian Mbappé masih memimpin, namun jaraknya dengan para pesaing sangat tipis. Lionel Messi dan Harry Kane membayangi ketat, sementara sejumlah pemain muda mulai mencuri perhatian.</p>\n<h2>Faktor babak gugur</h2>\n<p>Di fase gugur, peluang mencetak gol bisa berkurang karena laga cenderung lebih ketat dan taktis. Namun justru di sinilah para penyerang papan atas kerap menunjukkan kelasnya.</p>\n<h2>Bukan sekadar gol</h2>\n<p>Selain jumlah gol, kriteria seperti jumlah assist dan menit bermain menjadi penentu jika terjadi kesamaan angka. Persaingan diprediksi berlanjut hingga laga final.</p>\n"
  },
  {
    "slug": "rumor-transfer-pemain-bersinar-piala-dunia",
    "title": "Rumor Transfer: Klub-klub Eropa Incar Pemain Bersinar di Piala Dunia 2026",
    "excerpt": "Penampilan apik di turnamen membuat sejumlah nama jadi rebutan. Berikut bursa transfer yang mulai memanas.",
    "category": "Transfer",
    "author": "Indra Wijaya",
    "time": "9 jam lalu",
    "order": 11,
    "featured": false,
    "html": "<p>Piala Dunia kerap menjadi etalase bagi para pemain untuk menarik perhatian klub-klub besar. Edisi 2026 tak terkecuali, dengan bursa transfer yang mulai memanas bahkan sebelum turnamen usai.</p>\n<h2>Bintang baru lahir</h2>\n<p>Beberapa pemain muda yang tampil mengesankan langsung dikaitkan dengan raksasa Eropa. Performa di panggung terbesar dunia menaikkan nilai pasar mereka secara signifikan.</p>\n<h2>Klub bergerak cepat</h2>\n<p>Para pemandu bakat dan direktur olahraga dilaporkan sudah aktif memantau. Klub yang bergerak cepat berpeluang mendapatkan tanda tangan sang pemain sebelum harga melambung.</p>\n<h2>Hati-hati efek turnamen</h2>\n<p>Pengamat mengingatkan agar klub tidak terburu-buru. Tampil bagus dalam beberapa laga belum tentu menjamin konsistensi jangka panjang di kompetisi domestik yang lebih melelahkan.</p>\n"
  },
  {
    "slug": "preview-perempat-final-prancis-vs-spanyol",
    "title": "Preview Perempat Final: Prancis vs Spanyol, Duel Generasi Emas",
    "excerpt": "Dua kekuatan Eropa kembali bentrok di babak delapan besar. Siapa yang melaju ke semifinal?",
    "category": "Preview",
    "author": "Bayu Saputra",
    "time": "10 jam lalu",
    "order": 12,
    "featured": false,
    "html": "<p>Salah satu laga paling dinanti di babak perempat final mempertemukan <strong>Prancis</strong> dan <strong>Spanyol</strong>, dua negara dengan tradisi sepak bola menyerang yang memukau.</p>\n<h2>Kekuatan menyerang</h2>\n<p>Prancis mengandalkan kecepatan dan ketajaman lini depan, sementara Spanyol tampil dengan penguasaan bola dan kreativitas lini tengah yang sulit ditembus.</p>\n<h2>Titik penentu</h2>\n<p>Duel di lini tengah diprediksi menjadi kunci. Tim yang mampu mengontrol tempo permainan berpeluang besar menentukan hasil akhir.</p>\n<h2>Prediksi</h2>\n<p>Laga diperkirakan berjalan terbuka dan sarat gol. Pengalaman di laga-laga besar bisa menjadi pembeda tipis di antara kedua tim. Pemenang berhak melangkah ke semifinal dan semakin dekat dengan trofi.</p>\n"
  },
  {
    "slug": "highlight-gol-terbaik-fase-grup-piala-dunia-2026",
    "title": "Highlight: Lima Gol Terbaik Fase Grup Piala Dunia 2026",
    "excerpt": "Dari tendangan jarak jauh hingga gol salto, inilah gol-gol paling spektakuler sepanjang fase grup.",
    "category": "Highlight",
    "author": "Rangga Aditya",
    "time": "11 jam lalu",
    "order": 13,
    "featured": false,
    "html": "<p>Fase grup Piala Dunia 2026 menyuguhkan banyak momen tak terlupakan. Berikut lima gol terbaik yang paling banyak dibicarakan penggemar.</p>\n<h2>Daftar gol terbaik</h2>\n<ol>\n<li>Tendangan bebas melengkung dari luar kotak penalti</li>\n<li>Gol salto akrobatik di menit akhir</li>\n<li>Tendangan voli first-time menyambut umpan silang</li>\n<li>Solo run melewati empat pemain bertahan</li>\n<li>Tendangan jarak jauh yang menghujam pojok gawang</li>\n</ol>\n<h2>Kreativitas tanpa batas</h2>\n<p>Para pemain menunjukkan bahwa sepak bola tetap menjadi panggung seni. Setiap gol di atas tidak hanya soal hasil, tetapi juga keindahan eksekusi yang memukau jutaan penonton.</p>\n<h2>Pilihan penggemar</h2>\n<p>Voting gol terbaik turnamen masih dibuka. Penggemar dapat memberikan suara mereka untuk menentukan gol paling fenomenal sepanjang Piala Dunia 2026.</p>\n"
  },
  {
    "slug": "kejutan-tim-asia-piala-dunia-2026",
    "title": "Kejutan Tim Asia: Performa Wakil Benua Kuning di Piala Dunia 2026",
    "excerpt": "Sejumlah wakil Asia tampil di atas ekspektasi. Bagaimana peluang mereka melaju lebih jauh?",
    "category": "Piala Dunia",
    "author": "Dewi Lestari",
    "time": "Kemarin",
    "order": 14,
    "featured": false,
    "html": "<p>Wakil-wakil <strong>Asia</strong> kembali menjadi sorotan di Piala Dunia 2026. Beberapa tim tampil melampaui ekspektasi dan membuktikan jurang kualitas dengan tim Eropa serta Amerika Latin kian menyempit.</p>\n<h2>Modal disiplin dan kecepatan</h2>\n<p>Kekuatan tim Asia terletak pada disiplin taktik, stamina prima, dan transisi yang cepat. Pendekatan kolektif ini kerap merepotkan lawan yang di atas kertas lebih diunggulkan.</p>\n<h2>Lolosnya Indonesia</h2>\n<p>Salah satu cerita terbesar adalah lolosnya Timnas Indonesia ke babak gugur untuk pertama kali, menambah daftar prestasi sepak bola Asia di panggung dunia.</p>\n<h2>Peluang ke depan</h2>\n<p>Para pengamat menilai representasi Asia yang lebih banyak berkat format 48 tim memberi pengalaman berharga. Konsistensi dan pembinaan jangka panjang menjadi kunci untuk melangkah lebih jauh di masa depan.</p>\n"
  },
  {
    "slug": "teknologi-offside-semi-otomatis-piala-dunia-2026",
    "title": "Teknologi Offside Semi-Otomatis Jadi Andalan Piala Dunia 2026",
    "excerpt": "Keputusan offside kini lebih cepat dan akurat berkat sistem pelacakan canggih. Begini cara kerjanya.",
    "category": "Piala Dunia",
    "author": "Indra Wijaya",
    "time": "Kemarin",
    "order": 15,
    "featured": false,
    "html": "<p>Piala Dunia 2026 mengandalkan <strong>teknologi offside semi-otomatis</strong> untuk membantu wasit mengambil keputusan dengan lebih cepat dan akurat.</p>\n<h2>Cara kerja sistem</h2>\n<p>Sistem menggunakan banyak kamera pelacak yang memantau pergerakan setiap pemain dan bola secara real-time. Data ini kemudian diolah untuk menentukan posisi offside dalam hitungan detik.</p>\n<h2>Mengurangi kontroversi</h2>\n<p>Dengan visualisasi tiga dimensi, keputusan offside menjadi lebih transparan dan mudah dipahami penonton. Tujuannya adalah mengurangi perdebatan yang selama ini sering muncul.</p>\n<h2>Tetap ada peran manusia</h2>\n<p>Meski teknologi semakin canggih, keputusan akhir tetap berada di tangan wasit. Sistem ini berfungsi sebagai alat bantu, bukan pengganti penilaian manusia di lapangan.</p>\n"
  },
  {
    "slug": "maskot-resmi-piala-dunia-2026",
    "title": "Mengenal Maskot Resmi Piala Dunia 2026 dan Makna di Baliknya",
    "excerpt": "Tiga maskot mewakili tiga negara tuan rumah. Simak filosofi dan sambutan penggemar di seluruh dunia.",
    "category": "Piala Dunia",
    "author": "Tim Bolakami",
    "time": "Kemarin",
    "order": 16,
    "featured": false,
    "html": "<p>Sebagai bagian dari identitas turnamen, <strong>maskot resmi Piala Dunia 2026</strong> memperkenalkan karakter yang mewakili semangat tiga negara tuan rumah.</p>\n<h2>Filosofi maskot</h2>\n<p>Setiap maskot dirancang untuk mencerminkan budaya dan kekayaan alam Amerika Serikat, Kanada, dan Meksiko. Desainnya mengusung pesan persatuan dan keberagaman.</p>\n<h2>Sambutan penggemar</h2>\n<p>Kehadiran maskot disambut hangat, terutama oleh penonton muda. Merchandise resmi pun laris diburu sebagai kenang-kenangan dari turnamen bersejarah ini.</p>\n<h2>Lebih dari sekadar simbol</h2>\n<p>Maskot bukan sekadar hiasan. Ia menjadi duta yang mempromosikan nilai sportivitas, kebersamaan, dan kecintaan terhadap sepak bola kepada generasi penerus.</p>\n"
  },
  {
    "slug": "analisis-taktik-tim-favorit-juara",
    "title": "Analisis Taktik: Pendekatan Tim-tim Favorit Juara Piala Dunia 2026",
    "excerpt": "Dari penguasaan bola hingga pressing tinggi, beginilah ragam filosofi tim unggulan turnamen.",
    "category": "Preview",
    "author": "Bayu Saputra",
    "time": "2 hari lalu",
    "order": 17,
    "featured": false,
    "html": "<p>Menjelang fase krusial, ragam pendekatan taktik tim-tim favorit juara menjadi bahan diskusi menarik para pengamat sepak bola.</p>\n<h2>Penguasaan bola</h2>\n<p>Sejumlah tim tetap setia pada filosofi penguasaan bola, mengontrol tempo, dan melelahkan lawan melalui sirkulasi umpan yang sabar.</p>\n<h2>Pressing intensitas tinggi</h2>\n<p>Tim lain memilih pressing agresif untuk merebut bola di area lawan. Gaya ini menuntut stamina luar biasa, namun efektif menciptakan peluang dari kesalahan lawan.</p>\n<h2>Pragmatisme babak gugur</h2>\n<p>Di fase gugur, banyak tim cenderung lebih pragmatis. Keseimbangan antara bertahan solid dan serangan balik cepat sering kali menjadi formula yang ampuh untuk melaju jauh.</p>\n<h2>Faktor pembeda</h2>\n<p>Pada akhirnya, kedalaman skuad, kebugaran, dan ketenangan di momen krusial kerap menjadi penentu siapa yang berhak mengangkat trofi.</p>\n"
  },
  {
    "slug": "dampak-ekonomi-tuan-rumah-piala-dunia-2026",
    "title": "Dampak Ekonomi Piala Dunia 2026 bagi Tiga Negara Tuan Rumah",
    "excerpt": "Pariwisata, lapangan kerja, dan investasi infrastruktur melonjak. Berikut perkiraan manfaat ekonominya.",
    "category": "Piala Dunia",
    "author": "Indra Wijaya",
    "time": "2 hari lalu",
    "order": 18,
    "featured": false,
    "html": "<p>Menjadi tuan rumah Piala Dunia tidak hanya soal prestise, tetapi juga membawa <strong>dampak ekonomi</strong> yang signifikan bagi Amerika Serikat, Kanada, dan Meksiko.</p>\n<h2>Lonjakan pariwisata</h2>\n<p>Jutaan suporter dari seluruh dunia berdatangan, mendorong tingkat hunian hotel, restoran, dan sektor transportasi ke level tertinggi sepanjang tahun.</p>\n<h2>Lapangan kerja dan investasi</h2>\n<p>Penyelenggaraan turnamen menciptakan ribuan lapangan kerja sementara dan mendorong percepatan pembangunan infrastruktur di kota-kota penyelenggara.</p>\n<h2>Warisan jangka panjang</h2>\n<p>Selain manfaat jangka pendek, stadion dan fasilitas yang dibangun diharapkan menjadi warisan yang terus memberi nilai tambah bagi masyarakat setempat selama bertahun-tahun ke depan.</p>\n"
  },
  {
    "slug": "pemain-muda-bersinar-piala-dunia-2026",
    "title": "Wajah-wajah Muda yang Bersinar di Piala Dunia 2026",
    "excerpt": "Generasi baru talenta sepak bola unjuk gigi di panggung terbesar dunia. Inilah nama-nama yang patut diikuti.",
    "category": "Highlight",
    "author": "Rangga Aditya",
    "time": "3 hari lalu",
    "order": 19,
    "featured": false,
    "html": "<p>Piala Dunia selalu menjadi ajang lahirnya bintang baru. Edisi 2026 menghadirkan sejumlah <strong>pemain muda</strong> yang tampil mengesankan dan mencuri perhatian dunia.</p>\n<h2>Berani dan tanpa beban</h2>\n<p>Para pemain belia ini bermain tanpa beban, penuh percaya diri, dan kerap menjadi pembeda saat tim membutuhkan kreativitas. Keberanian mereka menyegarkan permainan tim.</p>\n<h2>Calon bintang masa depan</h2>\n<p>Beberapa di antaranya diprediksi akan menjadi wajah sepak bola dunia dalam satu dekade ke depan. Klub-klub besar pun mulai memantau perkembangan mereka.</p>\n<h2>Pentingnya pembinaan</h2>\n<p>Munculnya talenta muda ini menegaskan pentingnya akademi dan pembinaan usia dini. Investasi pada generasi muda terbukti membuahkan hasil di panggung tertinggi.</p>\n"
  },
  {
    "slug": "panduan-suporter-piala-dunia-2026",
    "title": "Panduan Suporter: Tips Menonton Piala Dunia 2026 di Amerika Utara",
    "excerpt": "Dari tiket, akomodasi, hingga zona waktu. Simak panduan praktis bagi penggemar yang ingin hadir langsung.",
    "category": "Piala Dunia",
    "author": "Dewi Lestari",
    "time": "3 hari lalu",
    "order": 20,
    "featured": false,
    "html": "<p>Bagi penggemar yang ingin menyaksikan langsung <strong>Piala Dunia 2026</strong>, persiapan matang sangat diperlukan mengingat luasnya wilayah penyelenggaraan.</p>\n<h2>Tiket dan akomodasi</h2>\n<p>Pesan tiket pertandingan jauh-jauh hari melalui kanal resmi untuk menghindari penipuan. Akomodasi sebaiknya dipesan sedini mungkin karena permintaan melonjak tinggi.</p>\n<h2>Perhatikan zona waktu</h2>\n<p>Dengan kota-kota yang tersebar lintas benua, perbedaan zona waktu cukup signifikan. Susun jadwal perjalanan dengan cermat agar tidak melewatkan laga favorit.</p>\n<h2>Nikmati atmosfernya</h2>\n<p>Selain pertandingan, manfaatkan festival penggemar dan area publik yang disediakan tuan rumah. Pengalaman berbaur dengan suporter dari berbagai negara adalah bagian tak terpisahkan dari pesona Piala Dunia.</p>\n"
  }
];
