// Build-time generator: reads markdown news in src/content/news/*.md,
// parses frontmatter + renders HTML, and writes a plain TS data module.
// This keeps node:fs / marked / gray-matter OUT of the Cloudflare Workers
// runtime bundle (the .md files are not deployed). Runtime reads the data only.
//
// Regenerate with: node scripts/generate-news.mjs
import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";
import { marked } from "marked";

const NEWS_DIR = path.join(process.cwd(), "src/content/news");
const OUT = path.join(process.cwd(), "src/lib/news.data.ts");

const files = fs.readdirSync(NEWS_DIR).filter((f) => f.endsWith(".md"));

const data = files
	.map((file) => {
		const raw = fs.readFileSync(path.join(NEWS_DIR, file), "utf8");
		const { data: fm, content } = matter(raw);
		const slug = file.replace(/\.md$/, "");
		return {
			slug,
			title: fm.title ?? slug,
			excerpt: fm.excerpt ?? "",
			category: fm.category ?? "Berita",
			author: fm.author ?? "Tim Bolakami",
			time: fm.time ?? "",
			order: typeof fm.order === "number" ? fm.order : 999,
			featured: fm.featured === true,
			html: marked.parse(content, { async: false }),
		};
	})
	.sort((a, b) => a.order - b.order);

const header =
	"// AUTO-GENERATED by scripts/generate-news.mjs — do not edit by hand.\n" +
	"// Regenerate with: node scripts/generate-news.mjs\n\n";

fs.writeFileSync(
	OUT,
	header + "export const newsData = " + JSON.stringify(data, null, 2) + ";\n",
);

console.log(`Generated ${data.length} articles -> src/lib/news.data.ts`);
